- hosts: all

  tasks:
  # cart
  - name: create docker image cart
    command: docker build -t cart-image:latest .
    args:
      chdir: /opt/docker/cart

  - name: create tag to image
    command: docker tag cart-image germansalguero711/cart-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/cart-image  
    
  - name: remove docker images from ansible server
    command: docker rmi cart-image:latest germansalguero711/cart-image
    ignore_errors: yes
  
  #producto
  - name: create docker image productos
    command: docker build -t productos-image:latest .
    args:
      chdir: /opt/docker/productos

  - name: create tag to image
    command: docker tag productos-image germansalguero711/productos-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/productos-image  
    
  - name: remove docker images from ansible server
    command: docker rmi productos-image:latest germansalguero711/productos-image
    ignore_errors: yes  
  
  #proveedores
  - name: create docker image proveedores
    command: docker build -t prov-image:latest .
    args:
      chdir: /opt/docker/microservicio-authProveedor

  - name: create tag to image
    command: docker tag prov-image germansalguero711/prov-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/prov-image  
    
  - name: remove docker images from ansible server
    command: docker rmi prov-image:latest germansalguero711/prov-image
    ignore_errors: yes  

  #clientes 
  - name: create docker image client
    command: docker build -t client-image:latest .
    args:
      chdir: /opt/docker/microservicio-authCliente

  - name: create tag to image
    command: docker tag client-image germansalguero711/client-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/client-image  
    
  - name: remove docker images from ansible server
    command: docker rmi client-image:latest germansalguero711/client-image
    ignore_errors: yes   
  
   #subasta 
  - name: create docker image subasta
    command: docker build -t subasta-image:latest .
    args:
      chdir: /opt/docker/microservicio-subasta

  - name: create tag to image
    command: docker tag subasta-image germansalguero711/subasta-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/subasta-image  
    
  - name: remove docker images from ansible server
    command: docker rmi subasta-image:latest germansalguero711/subasta-image
    ignore_errors: yes   

  #lista de deseos 
  - name: create docker image lista de deseos
    command: docker build -t lista-image:latest .
    args:
      chdir: /opt/docker/lista_deseos

  - name: create tag to image
    command: docker tag lista-image germansalguero711/lista-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/lista-image  
    
  - name: remove docker images from ansible server
    command: docker rmi lista-image:latest germansalguero711/lista-image
    ignore_errors: yes  

  #ESB
  - name: create docker image ESB
    command: docker build -t esb-image:latest .
    args:
      chdir: /opt/docker/Microservicio-ESB

  - name: create tag to image
    command: docker tag esb-image germansalguero711/esb-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/esb-image  
    
  - name: remove docker images from ansible server
    command: docker rmi esb-image:latest germansalguero711/esb-image
    ignore_errors: yes 


  #frontend.test
  # - name: create docker image test
  #   command: docker build -t test-image:latest -f dockerfile.test .
  #   args:
  #     chdir: /opt/docker/frontend/tangoCart

  # - name: create tag to image
  #   command: docker tag test-image germansalguero711/test-image

  # - name: push image on to dockerhub
  #   command: docker push germansalguero711/test-image  
    
  # - name: remove docker images from ansible server
  #   command: docker rmi test-image:latest germansalguero711/test-image
  #   ignore_errors: yes 

  #frontend.production
  - name: create docker image front
    command: docker build -t front-image:latest -f dockerfile.production .
    args:
      chdir: /opt/docker/frontend/tangoCart

  - name: create tag to image
    command: docker tag front-image germansalguero711/front-image

  - name: push image on to dockerhub
    command: docker push germansalguero711/front-image  
    
  - name: remove docker images from ansible server
    command: docker rmi front-image:latest germansalguero711/front-image
    ignore_errors: yes   
