version: '3.9'

services: 

  authcliente: 
      container_name: authCliente
      build:
          dockerfile: Dockerfile
          context: ./microservicio-authCliente # Lugar donde se encuentra el archivo 'Dockerfile'
      ports: 
        - 4000:4000

  authproveedor:
      container_name: authProveedor
      build:
          dockerfile: Dockerfile
          context: ./microservicio-authProveedor # Lugar donde se encuentra el archivo 'Dockerfile'
      ports: 
        - 4200:4200