version: '3.9'

services: 

  authcliente: 
      container_name: authcliente
      build:
          dockerfile: dockerfile
          context: ./microservicio-authCliente # Lugar donde se encuentra el archivo 'Dockerfile'
      ports: 
        - 4000:4000

  authproveedor:
      container_name: authproveedor
      build:
          dockerfile: Dockerfile
          context: ./microservicio-authProveedor # Lugar donde se encuentra el archivo 'Dockerfile'
      ports: 
        - 4001:4001
  
  cart_container:
      container_name: cart
      build:
          dockerfile: DockerFile
          context: ./cart # Lugar donde se encuentra el archivo 'Dockerfile'
      ports: 
        - 3001:3001

#   product_container:
#       container_name: cart
#       build:
#           dockerfile: Dockerfile
#           context: ./productos # Lugar donde se encuentra el archivo 'Dockerfile'
#       ports: 
#         - 3000:3000